In [1]:
import numpy as np

In [8]:
a = np.array([1,2])
a

array([1, 2])

In [10]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [13]:
a = np.zeros_like([4,5])
a

array([0, 0])

In [15]:
a = np.random.randint(1,10,7)
a

array([8, 3, 1, 7, 3, 6, 8])

In [16]:
a = np.random.random((2,3))
a

array([[0.89618789, 0.69411714, 0.76254874],
       [0.52636554, 0.51898512, 0.91828315]])

In [18]:
a = np.linspace(1,100,30)#按个数生成向量
a

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [19]:
a = np.arange(1,10,4)#按步长生成向量
a

array([1, 5, 9])

In [21]:
a = np.eye(4)#生成单位矩阵
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
a = np.full((3,3),9.9)
a

array([[9.9, 9.9, 9.9],
       [9.9, 9.9, 9.9],
       [9.9, 9.9, 9.9]])

In [4]:
a = np.array([1,2])
b = np.array([1,4,6])
np.concatenate([a,b])

array([1, 2, 1, 4, 6])